# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
