# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='username',
        ),
    ]
