# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20170224_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='poopyhead', max_length=45),
        ),
    ]
