# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('emailvalidation', '0002_auto_20170217_1527'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('validate', django.db.models.manager.Manager()),
            ],
        ),
    ]
