# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170224_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='activeUserPlanned',
            field=models.BooleanField(default=False),
        ),
    ]
