# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trips_activeuserplanned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joins',
            old_name='trips',
            new_name='trip',
        ),
    ]
