# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0002_auto_20170220_1645'),
        ('courses', '0002_auto_20170216_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logreg.Users')),
            ],
        ),
    ]
