# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='user_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liking', to='logreg.Users'),
        ),
    ]
