# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Secrets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logreg.Users')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='liked_secrets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_liked', to='dojo_secrets.Secrets'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logreg.Users'),
        ),
    ]
